###############################################################################
# phase5_diagnostic_panel_compare.R
#
# PURPOSE:
#   Cross-machine diagnostic: confirms that phase3_firm_exposure.RData (and
#   its inputs firm_year_belgian_euets and phase3_eua_prices) are identical
#   across local-1 and RMD.
#
#   Run this on BOTH machines after building the exposure panel and compare
#   the resulting fingerprint files. Any divergence localises the cause.
#
# OUTPUT:
#   output/tables/phase5_diagnostic_fingerprint.txt
#   output/tables/phase5_diagnostic_phase_aggregates.csv
###############################################################################

rm(list = ls())

library(dplyr)
library(digest)
library(stringr)

# ---- Paths ----
REPO_DIR <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile, winslash = "/")),
                     error = function(e) normalizePath(getwd(), winslash = "/"))
while (!file.exists(file.path(REPO_DIR, "paths.R"))) REPO_DIR <- dirname(REPO_DIR)
source(file.path(REPO_DIR, "paths.R"))

# ---- Load all three panels ----
load(file.path(PROC_DATA, "firm_year_belgian_euets.RData"))   # firm_year_belgian_euets
load(file.path(OUT_DATA,  "phase3_eua_prices.RData"))         # eua_prices_annual
load(file.path(OUT_DATA,  "phase3_firm_exposure.RData"))      # firm_exposure

# ---- Fingerprint helper ----
# Hash a data frame deterministically: sort by chosen keys, round numerics
# (so floating-point identical-up-to-rounding doesn't trip the hash), then
# digest the resulting string-cast.
fingerprint <- function(df, keys, round_digits = 6) {
  d <- df[do.call(order, df[keys]), , drop = FALSE]
  numerics <- sapply(d, is.numeric)
  d[numerics] <- lapply(d[numerics], function(x) round(x, round_digits))
  digest::digest(d, algo = "sha1")
}

# ---- Sink to fingerprint file ----
sink(file.path(OUTPUT_TAB, "phase5_diagnostic_fingerprint.txt"))

cat("================================================================\n")
cat("Phase 5 cross-machine diagnostic\n")
cat(sprintf("Generated by analysis/phase5_diagnostic_panel_compare.R\n"))
cat(sprintf("User:      %s\n", Sys.info()[["user"]]))
cat(sprintf("Hostname:  %s\n", Sys.info()[["nodename"]]))
cat(sprintf("R version: %s\n", R.version.string))
cat(sprintf("Date:      %s\n", Sys.Date()))
cat("================================================================\n\n")

# --------------------------------------------------------------
# Input 1: firm_year_belgian_euets
# --------------------------------------------------------------
cat("--- Input: firm_year_belgian_euets ---\n")
cat(sprintf("rows:                %d\n", nrow(firm_year_belgian_euets)))
cat(sprintf("cols:                %d\n", ncol(firm_year_belgian_euets)))
cat(sprintf("distinct vat:        %d\n", n_distinct(firm_year_belgian_euets$vat)))
cat(sprintf("year range:          %d-%d\n",
            min(firm_year_belgian_euets$year),
            max(firm_year_belgian_euets$year)))
cat(sprintf("in_sample == 1:      %d\n",
            sum(firm_year_belgian_euets$in_sample == 1, na.rm = TRUE)))
cat(sprintf("sum(emissions):      %.0f\n",
            sum(firm_year_belgian_euets$emissions, na.rm = TRUE)))
cat(sprintf("sum(allocated_free): %.0f\n",
            sum(firm_year_belgian_euets$allocated_free, na.rm = TRUE)))
cat(sprintf("sum(revenue):        %.0f\n",
            sum(firm_year_belgian_euets$revenue, na.rm = TRUE)))
cat(sprintf("SHA1 (sorted v,y):   %s\n",
            fingerprint(firm_year_belgian_euets, c("vat", "year"))))
cat("\n")

# --------------------------------------------------------------
# Input 2: eua_prices_annual
# --------------------------------------------------------------
cat("--- Input: eua_prices_annual ---\n")
cat(sprintf("rows:                %d\n", nrow(eua_prices_annual)))
cat(sprintf("year range:          %d-%d\n",
            min(eua_prices_annual$year),
            max(eua_prices_annual$year)))
cat(sprintf("source vector:       %s\n",
            paste(unique(eua_prices_annual$source), collapse = " | ")))
cat(sprintf("SHA1 (sorted year):  %s\n",
            fingerprint(eua_prices_annual, c("year"))))
cat("year-by-year prices:\n")
print(as.data.frame(eua_prices_annual[, c("year", "eua_price", "source")]),
      digits = 6)
cat("\n")

# --------------------------------------------------------------
# Output: firm_exposure
# --------------------------------------------------------------
cat("--- Output: firm_exposure ---\n")
cat(sprintf("rows:                %d\n", nrow(firm_exposure)))
cat(sprintf("cols:                %d\n", ncol(firm_exposure)))
cat(sprintf("distinct vat:        %d\n", n_distinct(firm_exposure$vat)))
cat(sprintf("year range:          %d-%d\n",
            min(firm_exposure$year), max(firm_exposure$year)))
cat(sprintf("cost_share_total def:%d (%.2f%%)\n",
            sum(!is.na(firm_exposure$cost_share_total)),
            100 * mean(!is.na(firm_exposure$cost_share_total))))
cat(sprintf("cost_share_total > 0:%d\n",
            sum(firm_exposure$cost_share_total > 0, na.rm = TRUE)))
cat(sprintf("sum(carbon_cost):    %.0f\n",
            sum(firm_exposure$carbon_cost, na.rm = TRUE)))
cat(sprintf("sum(shortage):       %.0f\n",
            sum(firm_exposure$shortage, na.rm = TRUE)))
cat(sprintf("sum(emissions):      %.0f\n",
            sum(firm_exposure$emissions, na.rm = TRUE)))
cat(sprintf("SHA1 (sorted v,y):   %s\n",
            fingerprint(firm_exposure, c("vat", "year"))))
cat("\n")

# --------------------------------------------------------------
# Per-phase aggregates and Moment 1 distribution (matches SHOCK_MAGNITUDE.md)
# --------------------------------------------------------------
cat("--- Per-phase aggregates ---\n")
phase_agg <- firm_exposure %>%
  filter(!is.na(cost_share_total)) %>%
  group_by(phase) %>%
  summarise(
    n_firm_years   = n(),
    n_distinct_firms = n_distinct(vat),
    sum_emissions  = sum(emissions, na.rm = TRUE),
    sum_shortage   = sum(shortage, na.rm = TRUE),
    sum_carbon_cost = sum(carbon_cost, na.rm = TRUE),
    p50  = quantile(cost_share_total, 0.50, na.rm = TRUE),
    p90  = quantile(cost_share_total, 0.90, na.rm = TRUE),
    p99  = quantile(cost_share_total, 0.99, na.rm = TRUE),
    mean = mean(cost_share_total, na.rm = TRUE),
    .groups = "drop"
  )
print(as.data.frame(phase_agg), digits = 4)
cat("\n")

# Same with five-phase split (matches Plan A Moment 1 exactly)
firm5 <- firm_exposure %>%
  filter(!is.na(cost_share_total)) %>%
  mutate(phase5 = case_when(
      year %in% 2005:2007 ~ "I",
      year %in% 2008:2012 ~ "II",
      year %in% 2013:2017 ~ "III pre-MSR",
      year %in% 2018:2020 ~ "III post-MSR",
      year >= 2021        ~ "IV"
    ))

cat("--- Five-phase split (matches Moment 1 in SHOCK_MAGNITUDE.md) ---\n")
phase5_agg <- firm5 %>%
  group_by(phase5) %>%
  summarise(
    n_firm_years     = n(),
    n_distinct_firms = n_distinct(vat),
    p50  = quantile(cost_share_total, 0.50),
    p90  = quantile(cost_share_total, 0.90),
    p99  = quantile(cost_share_total, 0.99),
    mean = mean(cost_share_total),
    .groups = "drop"
  )
print(as.data.frame(phase5_agg), digits = 4)
cat("\n")

cat("================================================================\n")
cat("If the SHA1 hashes match across machines, the panels are byte-\n")
cat("identical. If they differ, the per-phase aggregates above will\n")
cat("show which slice has diverged.\n")
cat("================================================================\n")

sink()

# Also dump the per-phase aggregate as CSV for easy diff
write.csv(phase5_agg,
          file.path(OUTPUT_TAB, "phase5_diagnostic_phase_aggregates.csv"),
          row.names = FALSE)

cat("Saved fingerprint to:", file.path(OUTPUT_TAB, "phase5_diagnostic_fingerprint.txt"), "\n")
cat("Saved aggregates  to:", file.path(OUTPUT_TAB, "phase5_diagnostic_phase_aggregates.csv"), "\n")
cat("\nDone.\n")
